name: CI

on:
  push:
    branches: [ main, feature/** ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint Python and Terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install Python dependencies
        run: |
          pip install flake8 mypy
      - name: Run flake8
        run: flake8 .
      - name: Run mypy
        run: mypy .
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
      - name: Terraform fmt check
        run: |
          cd infrastructure/environments/dev
          terraform fmt -check

  test-backend:
    name: Test Backend
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          pip install -r backend/requirements.txt
      - name: Run pytest
        run: pytest --maxfail=1 --disable-warnings -q

  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install and Build
        run: |
          npm install
          npm run build

  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v3
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0
      - name: Terraform Init
        run: |
          cd infrastructure/environments/dev
          terraform init -backend=false
      - name: Terraform Plan
        run: |
          cd infrastructure/environments/dev
          terraform plan